Updated 如何遞交項目 and How to submit
likecoin/likerthon pull request #5
Opened 2020-04-25 04:18 UTC by phoebepoon

Updated 如何遞交項目 and How to submit

2020-04-25 11:30 UTC, ckxpress requested changes
suggest to use hashtag #likerthon (eng, small "l") for all cases, which avoid some projects to use #讚客松 some #贊客松 and some simp chinese and some eng and projs got spread over a few hashtags

2020-04-26 05:39 UTC, phoebepoon commented
> suggest to use hashtag #likerthon (eng, small "l") for all cases, which avoid some projects to use #讚客松 some #贊客松 and some simp chinese and some eng and projs got spread over a few hashtags

Thanks and made above changes

2020-04-27 09:37 UTC, phoebepoon commented
> chinese version, need space after #likerthon

done

2020-04-27 09:40 UTC, ckxpress approved these changes

2020-04-27 09:40 UTC, merged